name: Build 
on:
  push:
  workflow_dispatch:
jobs:
  Build:
    runs-on: macos-latest
    steps:
     - name: Build App
       run: |
            git clone https://github.com/myaccount20232828/Booky
            cd Booky
            ls
            Scheme="Booky"
            XCProject="Booky.xcodeproj"
            xcodebuild -jobs $(sysctl -n hw.ncpu) -project "$XCProject" -scheme "$Scheme" -configuration Release -arch arm64 -sdk iphoneos -derivedDataPath "$TMPDIR/App" CODE_SIGNING_ALLOWED=NO DSTROOT=$AppTMP/install ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
            mkdir Payload
            mv "$(echo $TMPDIR/App/Build/Products/Release-iphoneos/*.app)" Payload
            zip -r9 "$Scheme.ipa" Payload
            rm -rf Payload && rm -rf "$TMPDIR/App"
     - name: Upload 
       uses: actions/upload-artifact@v3
       with:
         name: App.ipa
         path: "*/*.ipa"
